<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once __DIR__.'/../src/marketing/Growth.php';
use FAS\Marketing\Growth;
$checks=0;
function growthCheck($value,string $message):void {global $checks;$checks++;if(!$value)throw new RuntimeException($message);}
function growthFixture():array {
    $inventory=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
    $inventory->exec(file_get_contents(__DIR__.'/fixtures/applepay-schema.sql'));
    $clock=(object)['now'=>1800000000];
    $g=new Growth(new PDO('sqlite::memory:'),$inventory,['url'=>'https://fixture.invalid','reply_to_email'=>'reply@example.invalid'],fn()=>$clock->now);
    return [$g,$inventory,$clock];
}
function enableGrowth(Growth $g):void {$g->saveSettings(['from_email'=>'noreply@example.invalid','reply_to'=>'reply@example.invalid','postal_address'=>'Fixture PO Box 1, Test City, ZZ 00000','mail_enabled'=>'1']);}
function queuedPayload(Growth $g,string $kind):array {return json_decode($g->run('SELECT payload FROM growth_messages WHERE kind=? ORDER BY id DESC LIMIT 1',[$kind])->fetchColumn(),true);}
[$g,$db,$clock]=growthFixture();
growthCheck(!$g->ready(),'Email sends disabled by default');
$g->signup('Person@example.invalid');
$p=queuedPayload($g,'confirmation');
growthCheck($g->summary()['pending']===1 && $g->summary()['subscribers']===0,'Unconfirmed signups never count as subscribers');
$g->signup('person@example.invalid');
growthCheck($g->summary()['queued']===1,'Duplicate signup does not queue duplicate email');
growthCheck(!$g->confirm(str_repeat('f',64)),'Forged confirmation rejected');
growthCheck($g->confirm($p['confirm']),'Valid confirmation accepted');
growthCheck(!$g->confirm($p['confirm']),'Confirmation single use');
growthCheck($g->summary()['subscribers']===1,'Confirmed signup counted');
growthCheck($g->unsubscribe($p['unsubscribe']),'Unsubscribe works');
growthCheck($g->summary()['subscribers']===0,'Unsubscribe removes from active list');
[$g,$db,$clock]=growthFixture();
$g->signup('expired@example.invalid');$p=queuedPayload($g,'confirmation');$clock->now+=172801;
growthCheck(!$g->confirm($p['confirm']),'Expired confirmation rejected');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$owner=str_repeat('o',64);$items=[['id'=>1,'quantity'=>3,'price'=>0.01],['id'=>2,'quantity'=>99]];
$g->saveCart($owner,'buyer@example.invalid',$items,true);
$p=queuedPayload($g,'cart_link');
growthCheck($g->summary()['queued']===2,'Cart link and one delayed reminder queued');
$catalog=$g->restore($p['restore']);
growthCheck($catalog[0]['price']===10.0 && $catalog[1]['price']===15.0,'Restored prices are authoritative including sale price');
growthCheck($catalog[1]['quantity']===2,'Restored quantities clamped to current stock');
$db->exec("UPDATE products SET quantity=1,price=12.5 WHERE id=1;UPDATE products SET is_active=0 WHERE id=2");
$catalog=$g->restore($p['restore']);
growthCheck(count($catalog)===1 && $catalog[0]['quantity']===1 && $catalog[0]['price']===12.5,'Unavailable items omitted and changed prices refreshed');
$g->saveCart($owner,'buyer@example.invalid',[['id'=>1,'quantity'=>1]],true);
growthCheck($g->summary()['queued']===2,'Same cart re-save does not duplicate immediate email');
$sent=[];$send=function($m)use(&$sent){$sent[]=$m;return true;};
$result=$g->sendBatch($send);
growthCheck(count($sent)===1 && $result['sent']===1,'Only immediate cart link sends before abandonment window');
growthCheck(strpos($sent[0]['body'],'unsubscribe=')!==false && strpos($sent[0]['body'],'Fixture PO Box')!==false,'Email includes opt-out and postal address');
growthCheck(strpos($sent[0]['body'],'buyer@example.invalid')===false,'Customer email not embedded in restore link/body');
$clock->now+=86401;$g->sendBatch($send);
growthCheck(count($sent)===2,'Exactly one reminder after inactivity');
$g->sendBatch($send);growthCheck(count($sent)===2,'Worker rerun does not duplicate sends');
growthCheck($g->run("SELECT COUNT(*) FROM growth_messages WHERE payload<>'{}'")->fetchColumn()==0,'Sent message tokens removed from outbox');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$g->saveCart($owner,'buyer@example.invalid',[['id'=>1,'quantity'=>1]],false);
$p=queuedPayload($g,'cart_reminder');
growthCheck($g->summary()['queued']===1,'Checkout consent queues only one reminder');
$clock->now+=86000;$g->updateCart($owner,[['id'=>1,'quantity'=>2]]);$clock->now+=1000;
$sent=[];$result=$g->sendBatch($send);
growthCheck(count($sent)===0 && $g->summary()['queued']===1 && $result['deferred']===1 && $result['cancelled']===0,'Active cart postpones reminder without duplication or false cancellation');
$clock->now+=86401;
$db->exec("INSERT INTO orders(id,customer_email,payment_status,updated_at) VALUES(1,'buyer@example.invalid','pending','2027-01-01')");
$g->sendBatch($send);
growthCheck(count($sent)===0,'Uncertain/pending payment suppresses reminder');
growthCheck($g->run('SELECT status FROM growth_carts')->fetchColumn()==='payment_pending','Pending payment recorded separately');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$g->saveCart($owner,'buyer@example.invalid',[['id'=>1,'quantity'=>1]],false);$p=queuedPayload($g,'cart_reminder');
$g->restore($p['restore']);
$db->exec("INSERT INTO orders(id,customer_email,payment_status,updated_at) VALUES(1,'buyer@example.invalid','completed','2027-01-01')");
$clock->now+=86401;$sent=[];$g->sendBatch($send);
growthCheck(count($sent)===0 && $g->summary()['converted']===1,'Completed order suppresses reminder and records returned-cart order');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$g->saveCart($owner,'buyer@example.invalid',[['id'=>1,'quantity'=>1]],true);$p=queuedPayload($g,'cart_link');
growthCheck($g->unsubscribe($p['unsubscribe']),'Cart-only recipient can unsubscribe');
$g->saveCart(str_repeat('b',64),'buyer@example.invalid',[['id'=>1,'quantity'=>1]],true);
$sent=[];$g->sendBatch($send);
growthCheck(count($sent)===0,'Another visitor cannot override an email opt-out through cart capture');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$g->saveCart($owner,'buyer@example.invalid',[['id'=>1,'quantity'=>1]],true);
$g->saveCart(str_repeat('b',64),'buyer@example.invalid',[['id'=>1,'quantity'=>1]],true);
$sent=[];$g->sendBatch($send);
growthCheck(count($sent)===1,'Multiple carts for the same email respect address-wide email ceiling');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$g->saveCart($owner,'buyer@example.invalid',[['id'=>1,'quantity'=>1]],true);
$g->stopCart($owner);$sent=[];$g->sendBatch($send);
growthCheck(count($sent)===0,'Revoking cart consent cancels queued messages');
[$g,$db,$clock]=growthFixture();enableGrowth($g);
$g->signup('failure@example.invalid');
$g->sendBatch(function(){throw new RuntimeException('uncertain transport');});
growthCheck($g->run('SELECT status FROM growth_messages')->fetchColumn()==='uncertain','Unknown mail outcome retained for review');
$sent=[];$g->sendBatch($send);growthCheck(count($sent)===0,'Uncertain transport is never automatically resent');
echo "PASS $checks growth assertions; all mail transports mocked.\n";
