<?php
/**
 * eBay OAuth Callback Handler
 * Receives authorization code and exchanges it for access/refresh tokens
 */

require_once __DIR__ . '/auth.php';

$auth = new AdminAuth();
$auth->requireLogin();

// Check for errors from eBay
if (isset($_GET['error'])) {
    $errorDesc = $_GET['error_description'] ?? $_GET['error'];
    $_SESSION['error'] = 'eBay authorization failed: ' . htmlspecialchars($errorDesc);
    header('Location: settings.php');
    exit;
}

// Validate state parameter (CSRF protection)
$state = $_GET['state'] ?? '';
$expectedState = $_SESSION['ebay_oauth_state'] ?? '';

if (empty($state) || $state !== $expectedState) {
    $_SESSION['error'] = 'Invalid state parameter. Please try again.';
    header('Location: settings.php');
    exit;
}

// Get authorization code
$code = $_GET['code'] ?? '';
if (empty($code)) {
    $_SESSION['error'] = 'No authorization code received from eBay.';
    header('Location: settings.php');
    exit;
}

// Retrieve OAuth config from session
$oauthConfig = $_SESSION['ebay_oauth_config'] ?? [];
if (empty($oauthConfig)) {
    $_SESSION['error'] = 'OAuth configuration not found. Please try again.';
    header('Location: settings.php');
    exit;
}

$appId = $oauthConfig['app_id'];
$certId = $oauthConfig['cert_id'];
$sandbox = $oauthConfig['sandbox'];

// Determine token URL based on mode
if ($sandbox) {
    $tokenUrl = 'https://api.sandbox.ebay.com/identity/v1/oauth2/token';
} else {
    $tokenUrl = 'https://api.ebay.com/identity/v1/oauth2/token';
}

// Build callback URL (must match the one used in authorization)
$protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'];
$callbackUrl = $protocol . '://' . $host . dirname($_SERVER['PHP_SELF']) . '/ebay-oauth-callback.php';

// Prepare token exchange request
$credentials = base64_encode($appId . ':' . $certId);

$postData = [
    'grant_type' => 'authorization_code',
    'code' => $code,
    'redirect_uri' => $callbackUrl
];

$ch = curl_init($tokenUrl);
curl_setopt_array($ch, [
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => http_build_query($postData),
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_HTTPHEADER => [
        'Authorization: Basic ' . $credentials,
        'Content-Type: application/x-www-form-urlencoded'
    ]
]);

$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$error = curl_error($ch);
curl_close($ch);

// Handle errors
if ($error) {
    error_log('eBay OAuth token exchange error: ' . $error);
    $_SESSION['error'] = 'Failed to connect to eBay: ' . htmlspecialchars($error);
    header('Location: settings.php');
    exit;
}

if ($httpCode !== 200) {
    error_log('eBay OAuth token exchange failed. HTTP ' . $httpCode . ': ' . $response);
    $_SESSION['error'] = 'Failed to exchange authorization code (HTTP ' . $httpCode . '). Please check your eBay credentials.';
    header('Location: settings.php');
    exit;
}

// Parse response
$tokenData = json_decode($response, true);
if (!$tokenData || !isset($tokenData['refresh_token'])) {
    error_log('eBay OAuth invalid token response: ' . $response);
    $_SESSION['error'] = 'Invalid response from eBay. Please try again.';
    header('Location: settings.php');
    exit;
}

// The refresh token is the "User Token" we need
$userToken = $tokenData['refresh_token'];

// Load current config and update with new user token
$configFile = __DIR__ . '/../src/config/config.php';
$config = file_exists($configFile) ? require $configFile : [];

if (!isset($config['ebay'])) {
    $config['ebay'] = [];
}

$config['ebay']['user_token'] = $userToken;

// Write updated config
$configContent = "<?php\n/**\n * Configuration File\n * Generated by Admin Panel\n */\n\nreturn " . var_export($config, true) . ";\n";

if (file_put_contents($configFile, $configContent)) {
    // Clean up session data
    unset($_SESSION['ebay_oauth_state']);
    unset($_SESSION['ebay_oauth_config']);
    
    $_SESSION['success'] = 'eBay User Token obtained successfully! Your token is valid for 18 months.';
} else {
    $_SESSION['error'] = 'Failed to save User Token to configuration file. Check file permissions.';
}

header('Location: settings.php');
exit;
