<?php
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../src/utils/CSRF.php';
require_once __DIR__ . '/../src/utils/ShippingRules.php';

use FAS\Utils\CSRF;
use FAS\Utils\ShippingRules;

$auth = new AdminAuth();
$auth->requireLogin();

$success = '';
$error = '';
$configFile = __DIR__ . '/../src/config/config.php';
$configExampleFile = __DIR__ . '/../src/config/config.example.php';

if (!file_exists($configFile) && file_exists($configExampleFile)) {
    copy($configExampleFile, $configFile);
}

$config = file_exists($configFile) ? require $configFile : [];
$settings = ShippingRules::getFreeShippingSettings($config);

function fasShippingPositiveFloatOrNull($value): ?float
{
    if ($value === null || $value === '') {
        return null;
    }

    $number = (float)$value;
    return $number > 0 ? $number : null;
}

function fasShippingSettingValue(array $settings, string $field): string
{
    return $settings[$field] !== null ? (string)$settings[$field] : '';
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!CSRF::validateToken($_POST['csrf_token'] ?? '')) {
        $error = 'Invalid security token. Please try again.';
    } else {
        $settings = [
            'enabled' => isset($_POST['enabled']),
            'product_flags_enabled' => isset($_POST['product_flags_enabled']),
            'auto_rules_enabled' => isset($_POST['auto_rules_enabled']),
            'max_weight' => fasShippingPositiveFloatOrNull($_POST['max_weight'] ?? null),
            'max_length' => fasShippingPositiveFloatOrNull($_POST['max_length'] ?? null),
            'max_width' => fasShippingPositiveFloatOrNull($_POST['max_width'] ?? null),
            'max_height' => fasShippingPositiveFloatOrNull($_POST['max_height'] ?? null),
        ];

        $config['shipping']['free_shipping'] = $settings;
        $configContent = "<?php\n/**\n * Configuration File\n * Generated by Admin Panel\n */\n\nreturn " . var_export($config, true) . ";\n";

        if (file_put_contents($configFile, $configContent)) {
            $success = 'Free shipping settings saved successfully.';
        } else {
            $error = 'Failed to save settings. Check file permissions.';
        }
    }
}

$settings = ShippingRules::normalizeFreeShippingSettings($settings);
$hasAutoLimit = $settings['max_weight'] !== null
    || $settings['max_length'] !== null
    || $settings['max_width'] !== null
    || $settings['max_height'] !== null;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Free Shipping - Admin</title>
    <link rel="shortcut icon" href="../gallery/favicons/favicon.png">
    <link rel="manifest" href="/admin/manifest.json">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="css/admin-style.css">
</head>
<body class="bg-light">
<?php require __DIR__ . '/includes/nav.php'; ?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1><i class="fas fa-truck-fast me-2"></i>Free Shipping</h1>
    <?php if (!empty($settings['enabled'])): ?>
        <span class="badge bg-success fs-6 px-3 py-2">Enabled</span>
    <?php else: ?>
        <span class="badge bg-secondary fs-6 px-3 py-2">Disabled</span>
    <?php endif; ?>
</div>

<?php if ($success): ?>
    <div class="alert alert-success alert-dismissible fade show">
        <i class="fas fa-check-circle me-2"></i><?php echo htmlspecialchars($success); ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
<?php endif; ?>

<?php if ($error): ?>
    <div class="alert alert-danger alert-dismissible fade show">
        <i class="fas fa-exclamation-triangle me-2"></i><?php echo htmlspecialchars($error); ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
<?php endif; ?>

<div class="row g-4">
    <div class="col-lg-7">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0"><i class="fas fa-sliders me-2"></i>Global Rules</h5>
            </div>
            <div class="card-body">
                <form method="POST">
                    <?php echo CSRF::tokenField(); ?>

                    <div class="form-check form-switch mb-3">
                        <input class="form-check-input" type="checkbox" name="enabled" id="enabled" value="1" <?php echo !empty($settings['enabled']) ? 'checked' : ''; ?>>
                        <label class="form-check-label fw-semibold" for="enabled">Enable free shipping system</label>
                        <div class="form-text">Turns both product-level and automatic free-shipping rules on or off. Free shipping is limited to continental US delivery addresses.</div>
                    </div>

                    <div class="form-check form-switch mb-3">
                        <input class="form-check-input" type="checkbox" name="product_flags_enabled" id="product_flags_enabled" value="1" <?php echo !empty($settings['product_flags_enabled']) ? 'checked' : ''; ?>>
                        <label class="form-check-label fw-semibold" for="product_flags_enabled">Honor product-level free shipping flags</label>
                        <div class="form-text">Products marked in the product editor will ship free when this is enabled.</div>
                    </div>

                    <div class="form-check form-switch mb-4">
                        <input class="form-check-input" type="checkbox" name="auto_rules_enabled" id="auto_rules_enabled" value="1" <?php echo !empty($settings['auto_rules_enabled']) ? 'checked' : ''; ?>>
                        <label class="form-check-label fw-semibold" for="auto_rules_enabled">Automatically free ship small/light products</label>
                        <div class="form-text">A product must be at or below every threshold you fill in. Blank thresholds are ignored.</div>
                    </div>

                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label fw-semibold" for="max_weight">Maximum weight</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" class="form-control" name="max_weight" id="max_weight" value="<?php echo htmlspecialchars(fasShippingSettingValue($settings, 'max_weight')); ?>">
                                <span class="input-group-text">lbs</span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label fw-semibold" for="max_length">Maximum length</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" class="form-control" name="max_length" id="max_length" value="<?php echo htmlspecialchars(fasShippingSettingValue($settings, 'max_length')); ?>">
                                <span class="input-group-text">in</span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label fw-semibold" for="max_width">Maximum width</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" class="form-control" name="max_width" id="max_width" value="<?php echo htmlspecialchars(fasShippingSettingValue($settings, 'max_width')); ?>">
                                <span class="input-group-text">in</span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label fw-semibold" for="max_height">Maximum height</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" class="form-control" name="max_height" id="max_height" value="<?php echo htmlspecialchars(fasShippingSettingValue($settings, 'max_height')); ?>">
                                <span class="input-group-text">in</span>
                            </div>
                        </div>
                    </div>

                    <?php if (!empty($settings['auto_rules_enabled']) && !$hasAutoLimit): ?>
                        <div class="alert alert-warning mt-4 mb-0">
                            <i class="fas fa-triangle-exclamation me-2"></i>
                            Add at least one weight or dimension threshold before automatic rules can qualify products.
                        </div>
                    <?php endif; ?>

                    <button type="submit" class="btn btn-danger mt-4">
                        <i class="fas fa-save me-1"></i>Save Free Shipping Settings
                    </button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-5">
        <div class="card border-0 shadow-sm mb-4">
            <div class="card-header bg-white">
                <h5 class="mb-0"><i class="fas fa-circle-info me-2"></i>How It Works</h5>
            </div>
            <div class="card-body">
                <ul class="mb-0 ps-3">
                    <li>Manual product flags are set on each product edit page.</li>
                    <li>Automatic rules evaluate product weight and dimensions stored in the catalog.</li>
                    <li>Free shipping only applies after checkout confirms a continental US address.</li>
                    <li>Alaska, Hawaii, US territories, and military postal regions are excluded.</li>
                    <li>Free-shipping items are removed from rated parcels during checkout for eligible addresses.</li>
                    <li>If every cart item qualifies, checkout shows a $0 Free Shipping method.</li>
                    <li>If the cart is mixed, shoppers only pay shipping on non-qualified items.</li>
                </ul>
            </div>
        </div>

        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0"><i class="fas fa-list-check me-2"></i>Current Rule Summary</h5>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between border-bottom py-2">
                    <span>Product flags</span>
                    <strong><?php echo !empty($settings['product_flags_enabled']) ? 'On' : 'Off'; ?></strong>
                </div>
                <div class="d-flex justify-content-between border-bottom py-2">
                    <span>Auto small/light rule</span>
                    <strong><?php echo !empty($settings['auto_rules_enabled']) ? 'On' : 'Off'; ?></strong>
                </div>
                <div class="small text-muted mt-3">
                    Thresholds apply only when the auto rule is enabled and the product has matching catalog dimensions.
                </div>
            </div>
        </div>
    </div>
</div>

<?php require __DIR__ . '/includes/footer.php'; ?>
