<?php
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../src/utils/CSRF.php';

use FAS\Utils\CSRF;

$auth = new AdminAuth();
$auth->requireLogin();

$success = '';
$error   = '';

$configFile = __DIR__ . '/../src/config/config.php';
$config     = file_exists($configFile) ? require $configFile : [];
$sale       = $config['sale'] ?? [
    'enabled'   => false,
    'type'      => 'percentage',
    'value'     => 0,
    'label'     => 'SALE',
    'starts_at' => '',
    'ends_at'   => '',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!CSRF::validateToken($_POST['csrf_token'] ?? '')) {
        $error = 'Invalid security token. Please try again.';
    } else {
        $type  = in_array($_POST['type'] ?? '', ['percentage', 'fixed'], true)
                    ? $_POST['type']
                    : 'percentage';
        $value = max(0, (float) ($_POST['value'] ?? 0));

        // Clamp percentage to 0–99
        if ($type === 'percentage') {
            $value = min(99, $value);
        }

        $startsAt = !empty($_POST['starts_at']) ? $_POST['starts_at'] : null;
        $endsAt   = !empty($_POST['ends_at'])   ? $_POST['ends_at']   : null;

        // Validate datetime values
        if ($startsAt !== null && strtotime($startsAt) === false) {
            $error = 'Invalid "Starts At" date/time.';
        } elseif ($endsAt !== null && strtotime($endsAt) === false) {
            $error = 'Invalid "Ends At" date/time.';
        } else {

        $sale = [
            'enabled'   => isset($_POST['enabled']),
            'type'      => $type,
            'value'     => $value,
            'label'     => trim($_POST['label'] ?? 'SALE'),
            'starts_at' => $startsAt,
            'ends_at'   => $endsAt,
        ];

        // Read the current full config and replace only the 'sale' key
        $config['sale'] = $sale;

        $configContent = "<?php\n/**\n * Configuration File\n * Generated by Admin Panel\n */\n\nreturn " . var_export($config, true) . ";\n";

        if (file_put_contents($configFile, $configContent)) {
            $success = 'Sale settings saved successfully!';
        } else {
            $error = 'Failed to save settings. Check file permissions.';
        }
        } // end date validation
    }
}

// Determine whether the sale is currently live
$saleIsLive = false;
if (!empty($sale['enabled'])) {
    $now       = time();
    $startOk   = empty($sale['starts_at']) || (($ts = strtotime($sale['starts_at'])) !== false && $ts <= $now);
    $endOk     = empty($sale['ends_at'])   || (($ts = strtotime($sale['ends_at']))   !== false && $ts >= $now);
    $saleIsLive = $startOk && $endOk;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site-Wide Sale - Admin</title>
    <link rel="shortcut icon" href="../gallery/favicons/favicon.png">
    <link rel="manifest" href="/admin/manifest.json">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="css/admin-style.css">
</head>
<body class="bg-light">
    <?php include __DIR__ . '/includes/nav.php'; ?>

    <div class="admin-hero d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-3">
        <h1>
            <i class="fas fa-percent me-2"></i>Site-Wide Sale
        </h1>
        <?php if ($saleIsLive): ?>
            <span class="badge bg-success fs-6 px-3 py-2">
                <i class="fas fa-check-circle me-1"></i>Sale is LIVE
            </span>
        <?php elseif (!empty($sale['enabled'])): ?>
            <span class="badge bg-warning text-dark fs-6 px-3 py-2">
                <i class="fas fa-clock me-1"></i>Sale Enabled (outside schedule)
            </span>
        <?php else: ?>
            <span class="badge bg-secondary fs-6 px-3 py-2">
                <i class="fas fa-times-circle me-1"></i>Sale is OFF
            </span>
        <?php endif; ?>
    </div>

    <?php if ($success): ?>
        <div class="alert alert-success alert-dismissible fade show">
            <i class="fas fa-check-circle me-2"></i><?php echo htmlspecialchars($success); ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    <?php endif; ?>

    <?php if ($error): ?>
        <div class="alert alert-danger alert-dismissible fade show">
            <i class="fas fa-exclamation-triangle me-2"></i><?php echo htmlspecialchars($error); ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    <?php endif; ?>

    <div class="row">
        <!-- Settings form -->
        <div class="col-lg-7">
            <div class="card border-0 shadow-sm mb-4">
                <div class="card-header bg-white">
                    <h5 class="mb-0"><i class="fas fa-cog me-2"></i>Sale Configuration</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <?php echo CSRF::tokenField(); ?>

                        <div class="mb-3 form-check form-switch">
                            <input type="checkbox" class="form-check-input" name="enabled" id="enabled"
                                   value="1" <?php echo !empty($sale['enabled']) ? 'checked' : ''; ?>>
                            <label class="form-check-label fw-semibold" for="enabled">Enable Site-Wide Sale</label>
                            <div class="form-text">When enabled, all products will display a reduced price.</div>
                        </div>

                        <hr>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label class="form-label fw-semibold">Discount Type</label>
                                <select name="type" id="type" class="form-select" onchange="updatePreview()">
                                    <option value="percentage" <?php echo ($sale['type'] ?? 'percentage') === 'percentage' ? 'selected' : ''; ?>>
                                        Percentage (%)
                                    </option>
                                    <option value="fixed" <?php echo ($sale['type'] ?? '') === 'fixed' ? 'selected' : ''; ?>>
                                        Fixed Amount ($)
                                    </option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label fw-semibold">
                                    Discount Value <span id="typeUnit" class="text-muted">(e.g. 20 for 20%)</span>
                                </label>
                                <input type="number" name="value" id="value" class="form-control"
                                       value="<?php echo htmlspecialchars((string) ($sale['value'] ?? 0)); ?>"
                                       min="0" step="0.01" required oninput="updatePreview()">
                            </div>
                        </div>

                        <div class="mb-3">
                            <label class="form-label fw-semibold">Badge Label</label>
                            <input type="text" name="label" class="form-control"
                                   value="<?php echo htmlspecialchars($sale['label'] ?? 'SALE'); ?>"
                                   placeholder="e.g. SALE, CLEARANCE, SUMMER SALE" maxlength="30">
                            <div class="form-text">Short text shown on product cards. Leave blank for "Save X%" auto-label.</div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label class="form-label fw-semibold">Starts At <small class="text-muted">(optional)</small></label>
                                <input type="datetime-local" name="starts_at" class="form-control"
                                       value="<?php echo htmlspecialchars($sale['starts_at'] ?? ''); ?>">
                            </div>
                            <div class="col-md-6">
                                <label class="form-label fw-semibold">Ends At <small class="text-muted">(optional)</small></label>
                                <input type="datetime-local" name="ends_at" class="form-control"
                                       value="<?php echo htmlspecialchars($sale['ends_at'] ?? ''); ?>">
                            </div>
                        </div>
                        <div class="form-text mb-3">Leave both dates blank to run indefinitely while the toggle is on.</div>

                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-save me-1"></i>Save Sale Settings
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Live preview + info panel -->
        <div class="col-lg-5">
            <div class="card border-0 shadow-sm mb-4">
                <div class="card-header bg-white">
                    <h5 class="mb-0"><i class="fas fa-eye me-2"></i>Price Preview</h5>
                </div>
                <div class="card-body">
                    <p class="text-muted small mb-3">How a $100 product will look with current settings:</p>
                    <div id="preview-card" class="border rounded p-3 bg-light">
                        <div class="mb-1">
                            <span id="preview-price" class="fs-4 fw-bold text-danger">$100.00</span>
                            <span id="preview-original" class="text-muted text-decoration-line-through ms-2" style="display:none;"></span>
                        </div>
                        <div id="preview-badge" style="display:none;">
                            <span class="badge bg-danger" id="preview-badge-text"></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card border-0 shadow-sm">
                <div class="card-header bg-white">
                    <h5 class="mb-0"><i class="fas fa-info-circle me-2"></i>How It Works</h5>
                </div>
                <div class="card-body small text-muted">
                    <ul class="ps-3 mb-0">
                        <li class="mb-1">All products on the <strong>Products</strong> and <strong>Product Detail</strong> pages display the sale price with the original price crossed out.</li>
                        <li class="mb-1">Products that already have an individual <em>sale_price</em> will show whichever discount is greater.</li>
                        <li class="mb-1">The discounted price is the price added to cart — no coupon code required.</li>
                        <li class="mb-1">Use the optional start/end dates to schedule the sale in advance.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
    function updatePreview() {
        var type  = document.getElementById('type').value;
        var value = parseFloat(document.getElementById('value').value) || 0;
        var base  = 100.00;

        document.getElementById('typeUnit').textContent =
            type === 'percentage' ? '(0–99, e.g. 20 for 20% off)' : '(e.g. 5 for $5 off)';

        var salePrice;
        if (type === 'percentage' && value > 0 && value < 100) {
            salePrice = Math.round(base * (1 - value / 100) * 100) / 100;
        } else if (type === 'fixed' && value > 0) {
            salePrice = Math.max(0.01, Math.round((base - value) * 100) / 100);
        } else {
            salePrice = null;
        }

        var priceEl    = document.getElementById('preview-price');
        var origEl     = document.getElementById('preview-original');
        var badgeEl    = document.getElementById('preview-badge');
        var badgeText  = document.getElementById('preview-badge-text');

        if (salePrice !== null && salePrice < base) {
            priceEl.textContent   = '$' + salePrice.toFixed(2);
            origEl.textContent    = '$' + base.toFixed(2);
            origEl.style.display  = 'inline';
            badgeEl.style.display = 'block';
            var pct = Math.round((base - salePrice) / base * 100);
            badgeText.textContent = 'Save ' + pct + '%';
        } else {
            priceEl.textContent   = '$' + base.toFixed(2);
            origEl.style.display  = 'none';
            badgeEl.style.display = 'none';
        }
    }
    document.addEventListener('DOMContentLoaded', updatePreview);
    </script>

    <?php include __DIR__ . '/includes/footer.php'; ?>
</body>
</html>
