<?php
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../src/config/Database.php';

$auth = new AdminAuth();
$auth->requireLogin();

$success = '';
$error = '';

// Load current config
$configFile = __DIR__ . '/../src/config/config.php';
$configExampleFile = __DIR__ . '/../src/config/config.example.php';

if (!file_exists($configFile)) {
    if (file_exists($configExampleFile)) {
        copy($configExampleFile, $configFile);
    }
}

$config = file_exists($configFile) ? require $configFile : [];

// Handle config update
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $newConfig = [
        'database' => [
            'host' => $_POST['db_host'] ?? 'localhost',
            'database' => $_POST['db_name'] ?? 'flipandstrip',
            'username' => $_POST['db_user'] ?? 'root',
            'password' => $_POST['db_password'] ?? '',
            'charset' => 'utf8mb4'
        ],
        'ebay' => [
            'app_id' => $_POST['ebay_app_id'] ?? '',
            'cert_id' => $_POST['ebay_cert_id'] ?? '',
            'dev_id' => $_POST['ebay_dev_id'] ?? '',
            'user_token' => $_POST['ebay_user_token'] ?? '',
            'sandbox' => isset($_POST['ebay_sandbox']),
            'site_id' => (int)($_POST['ebay_site_id'] ?? 0),
            'store_name' => $_POST['ebay_store_name'] ?? 'moto800'
        ],
        'paypal' => [
            'client_id' => $_POST['paypal_client_id'] ?? '',
            'client_secret' => $_POST['paypal_client_secret'] ?? '',
            'mode' => $_POST['paypal_mode'] ?? 'sandbox',
            'currency' => $_POST['paypal_currency'] ?? 'USD'
        ],
        'easyship' => [
            'api_key' => $_POST['easyship_api_key'] ?? '',
            'platform_name' => $_POST['easyship_platform_name'] ?? 'Flip and Strip',
            'platform_order_number_prefix' => $_POST['easyship_prefix'] ?? 'FAS'
        ],
        'tawk' => [
            'enabled' => isset($_POST['tawk_enabled']),
            'property_id' => $_POST['tawk_property_id'] ?? '',
            'widget_id' => $_POST['tawk_widget_id'] ?? ''
        ],
        'turnstile' => [
            'enabled' => isset($_POST['turnstile_enabled']),
            'site_key' => $_POST['turnstile_site_key'] ?? '',
            'secret_key' => ($_POST['turnstile_secret_key'] ?? '') === '••••••••••••••••' 
                ? ($config['turnstile']['secret_key'] ?? '') 
                : ($_POST['turnstile_secret_key'] ?? '')
        ],
        'site' => [
            'name' => $_POST['site_name'] ?? 'Flip and Strip',
            'url' => $_POST['site_url'] ?? 'https://flipandstrip.com',
            'email' => $_POST['site_email'] ?? 'info@flipandstrip.com',
            'phone' => $_POST['site_phone'] ?? ''
        ],
        'security' => [
            'sync_api_key' => $_POST['sync_api_key'] ?? 'fas_sync_key_2026',
            'admin_password_salt' => $config['security']['admin_password_salt'] ?? 'CHANGE_THIS_SALT'
        ]
    ];
    
    // Write config file
    $configContent = "<?php\n/**\n * Configuration File\n * Generated by Admin Panel\n */\n\nreturn " . var_export($newConfig, true) . ";\n";
    
    if (file_put_contents($configFile, $configContent)) {
        $success = 'Settings saved successfully';
        $config = $newConfig;
    } else {
        $error = 'Failed to save settings. Check file permissions.';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Settings - Admin Panel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="css/admin-style.css">
</head>
<body class="bg-light">
    <?php include __DIR__ . '/includes/nav.php'; ?>
                <h1 class="mb-4">Settings</h1>

                <?php if ($success): ?>
                    <div class="alert alert-success alert-dismissible fade show">
                        <i class="fas fa-check-circle me-2"></i><?php echo htmlspecialchars($success); ?>
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                <?php endif; ?>

                <?php if ($error): ?>
                    <div class="alert alert-danger alert-dismissible fade show">
                        <i class="fas fa-exclamation-triangle me-2"></i><?php echo htmlspecialchars($error); ?>
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                <?php endif; ?>

                <form method="POST">
                    <!-- Database Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="fas fa-database me-2"></i>Database Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Host</label>
                                    <input type="text" class="form-control" name="db_host" value="<?php echo htmlspecialchars($config['database']['host'] ?? 'localhost'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Database Name</label>
                                    <input type="text" class="form-control" name="db_name" value="<?php echo htmlspecialchars($config['database']['database'] ?? 'flipandstrip'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Username</label>
                                    <input type="text" class="form-control" name="db_user" value="<?php echo htmlspecialchars($config['database']['username'] ?? 'root'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Password</label>
                                    <input type="password" class="form-control" name="db_password" value="<?php echo htmlspecialchars($config['database']['password'] ?? ''); ?>" placeholder="Leave blank to keep current">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- eBay API Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="fas fa-store me-2"></i>eBay API Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">App ID</label>
                                    <input type="text" class="form-control" name="ebay_app_id" value="<?php echo htmlspecialchars($config['ebay']['app_id'] ?? ''); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Cert ID</label>
                                    <input type="text" class="form-control" name="ebay_cert_id" value="<?php echo htmlspecialchars($config['ebay']['cert_id'] ?? ''); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Dev ID</label>
                                    <input type="text" class="form-control" name="ebay_dev_id" value="<?php echo htmlspecialchars($config['ebay']['dev_id'] ?? ''); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">User Token 
                                        <a href="ebay-token-guide.php" class="text-decoration-none" target="_blank">
                                            <i class="bi bi-question-circle"></i> How to obtain?
                                        </a>
                                    </label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="ebay_user_token" value="<?php echo htmlspecialchars($config['ebay']['user_token'] ?? ''); ?>" placeholder="Your eBay User Token">
                                        <a href="ebay-oauth.php" class="btn btn-primary" title="Generate User Token using OAuth">
                                            <i class="bi bi-key"></i> Get User Token
                                        </a>
                                    </div>
                                    <small class="text-muted">Required for syncing products from your eBay store. Click "Get User Token" to automatically obtain it using OAuth.</small>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Store Name</label>
                                    <input type="text" class="form-control" name="ebay_store_name" value="<?php echo htmlspecialchars($config['ebay']['store_name'] ?? 'moto800'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Site ID</label>
                                    <select class="form-select" name="ebay_site_id">
                                        <option value="0" <?php echo ($config['ebay']['site_id'] ?? 0) == 0 ? 'selected' : ''; ?>>US (0)</option>
                                        <option value="2" <?php echo ($config['ebay']['site_id'] ?? 0) == 2 ? 'selected' : ''; ?>>Canada (2)</option>
                                        <option value="3" <?php echo ($config['ebay']['site_id'] ?? 0) == 3 ? 'selected' : ''; ?>>UK (3)</option>
                                    </select>
                                </div>
                                <div class="col-12 mb-3">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" name="ebay_sandbox" id="ebay_sandbox" <?php echo !empty($config['ebay']['sandbox']) ? 'checked' : ''; ?>>
                                        <label class="form-check-label" for="ebay_sandbox">Use Sandbox Mode</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- PayPal Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="bi bi-credit-card me-2"></i>PayPal Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Client ID</label>
                                    <input type="text" class="form-control" name="paypal_client_id" value="<?php echo htmlspecialchars($config['paypal']['client_id'] ?? ''); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Client Secret</label>
                                    <input type="text" class="form-control" name="paypal_client_secret" value="<?php echo htmlspecialchars($config['paypal']['client_secret'] ?? ''); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Mode</label>
                                    <select class="form-select" name="paypal_mode">
                                        <option value="sandbox" <?php echo ($config['paypal']['mode'] ?? 'sandbox') == 'sandbox' ? 'selected' : ''; ?>>Sandbox</option>
                                        <option value="live" <?php echo ($config['paypal']['mode'] ?? 'sandbox') == 'live' ? 'selected' : ''; ?>>Live</option>
                                    </select>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Currency</label>
                                    <input type="text" class="form-control" name="paypal_currency" value="<?php echo htmlspecialchars($config['paypal']['currency'] ?? 'USD'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- EasyShip Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="bi bi-truck me-2"></i>EasyShip Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <label class="form-label">API Key</label>
                                    <input type="text" class="form-control" name="easyship_api_key" value="<?php echo htmlspecialchars($config['easyship']['api_key'] ?? ''); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Platform Name</label>
                                    <input type="text" class="form-control" name="easyship_platform_name" value="<?php echo htmlspecialchars($config['easyship']['platform_name'] ?? 'Flip and Strip'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Order Number Prefix</label>
                                    <input type="text" class="form-control" name="easyship_prefix" value="<?php echo htmlspecialchars($config['easyship']['platform_order_number_prefix'] ?? 'FAS'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Tawk.to Chat Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="bi bi-chat-dots me-2"></i>Tawk.to Live Chat Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="mb-3">
                                <div class="form-check form-switch">
                                    <input type="checkbox" class="form-check-input" name="tawk_enabled" id="tawk_enabled" <?php echo !empty($config['tawk']['enabled']) ? 'checked' : ''; ?>>
                                    <label class="form-check-label" for="tawk_enabled">Enable Tawk.to Live Chat</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Property ID</label>
                                    <input type="text" class="form-control" name="tawk_property_id" value="<?php echo htmlspecialchars($config['tawk']['property_id'] ?? ''); ?>" placeholder="e.g., 5f8b3c2d4e1234567890abcd">
                                    <small class="text-muted">Found in your Tawk.to dashboard</small>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Widget ID</label>
                                    <input type="text" class="form-control" name="tawk_widget_id" value="<?php echo htmlspecialchars($config['tawk']['widget_id'] ?? ''); ?>" placeholder="e.g., default">
                                    <small class="text-muted">Usually "default" or a custom ID</small>
                                </div>
                            </div>
                            <div class="alert alert-info">
                                <i class="fas fa-circle-info me-2"></i>
                                <strong>How to get your Tawk.to IDs:</strong><br>
                                1. Sign up or log in at <a href="https://tawk.to" target="_blank" class="alert-link">tawk.to</a><br>
                                2. Go to Administration > Channels > Chat Widget<br>
                                3. Copy the Property ID and Widget ID from the widget code
                            </div>
                        </div>
                    </div>

                    <!-- Turnstile Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="fas fa-shield-alt me-2"></i>Cloudflare Turnstile Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="mb-3">
                                <div class="form-check form-switch">
                                    <input type="checkbox" class="form-check-input" name="turnstile_enabled" id="turnstile_enabled" <?php echo !empty($config['turnstile']['enabled']) ? 'checked' : ''; ?>>
                                    <label class="form-check-label" for="turnstile_enabled">Enable Turnstile on Contact Form</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Site Key</label>
                                    <input type="text" class="form-control" name="turnstile_site_key" value="<?php echo htmlspecialchars($config['turnstile']['site_key'] ?? ''); ?>" placeholder="Your Cloudflare Turnstile site key">
                                    <small class="text-muted">Public key shown to users</small>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Secret Key</label>
                                    <input type="password" class="form-control" name="turnstile_secret_key" value="<?php echo !empty($config['turnstile']['secret_key']) ? '••••••••••••••••' : ''; ?>" placeholder="Your Cloudflare Turnstile secret key">
                                    <small class="text-muted">Private key for server-side verification. Leave as-is to keep current key.</small>
                                </div>
                            </div>
                            <div class="alert alert-info">
                                <i class="fas fa-circle-info me-2"></i>
                                <strong>How to get your Turnstile keys:</strong><br>
                                1. Sign up or log in at <a href="https://dash.cloudflare.com" target="_blank" class="alert-link">Cloudflare Dashboard</a><br>
                                2. Go to Turnstile section<br>
                                3. Create a new site or use an existing one<br>
                                4. Copy the Site Key and Secret Key<br>
                                <strong>Note:</strong> Turnstile helps protect your contact form from spam and bot submissions.
                            </div>
                        </div>
                    </div>

                    <!-- Site Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="fas fa-globe me-2"></i>Site Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Site Name</label>
                                    <input type="text" class="form-control" name="site_name" value="<?php echo htmlspecialchars($config['site']['name'] ?? 'Flip and Strip'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Site URL</label>
                                    <input type="url" class="form-control" name="site_url" value="<?php echo htmlspecialchars($config['site']['url'] ?? 'https://flipandstrip.com'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Email</label>
                                    <input type="email" class="form-control" name="site_email" value="<?php echo htmlspecialchars($config['site']['email'] ?? 'info@flipandstrip.com'); ?>">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Phone</label>
                                    <input type="tel" class="form-control" name="site_phone" value="<?php echo htmlspecialchars($config['site']['phone'] ?? ''); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Security Settings -->
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-header bg-white">
                            <h5 class="mb-0"><i class="bi bi-shield-check me-2"></i>Security Settings</h5>
                        </div>
                        <div class="card-body">
                            <div class="mb-3">
                                <label class="form-label">
                                    Sync API Key
                                    <i class="bi bi-question-circle text-muted" 
                                       data-bs-toggle="tooltip" 
                                       title="Security token used to authenticate API sync requests. Change this to a random string for better security."></i>
                                </label>
                                <input type="text" class="form-control font-monospace" name="sync_api_key" value="<?php echo htmlspecialchars($config['security']['sync_api_key'] ?? 'fas_sync_key_2026'); ?>">
                                <small class="text-muted">
                                    This key is used to protect the sync endpoint from unauthorized access. 
                                    It's automatically used by the admin panel, but you'll need it if calling the API directly: 
                                    <code>/api/ebay-sync.php?key=YOUR_KEY</code>
                                </small>
                            </div>
                            <div class="alert alert-warning">
                                <i class="bi bi-shield-exclamation me-2"></i>
                                <strong>Security Tip:</strong> Change the default sync key to a long, random string to prevent unauthorized sync requests.
                            </div>
                        </div>
                    </div>

                    <div class="mb-4">
                        <button type="submit" class="btn btn-danger btn-lg">
                            <i class="fas fa-check-circle me-2"></i>Save Settings
                        </button>
                        <a href="index.php" class="btn btn-secondary btn-lg">Cancel</a>
                    </div>
                </form>

    <?php include __DIR__ . '/includes/footer.php'; ?>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Initialize Bootstrap tooltips
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
</body>
</html>
