<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once __DIR__.'/../src/payments/PayPalWebhookSetup.php';
use FAS\Payments\PayPalWebhookSetup;

try {
    $command = $argv[1] ?? 'check';
    if (!in_array($command, ['check', 'setup'], true)) {
        throw new RuntimeException('Usage: php scripts/paypal-webhook-setup.php check|setup');
    }
    $config = require __DIR__.'/../src/config/config.php';
    $base = rtrim((string)($config['site']['url'] ?? ''), '/');
    if (!filter_var($base, FILTER_VALIDATE_URL) || parse_url($base, PHP_URL_SCHEME) !== 'https'
        || parse_url($base, PHP_URL_USER) || parse_url($base, PHP_URL_QUERY) || parse_url($base, PHP_URL_FRAGMENT)) {
        throw new RuntimeException('Set site.url to the checkout site HTTPS base URL.');
    }
    $url = $base.'/api/paypal-webhook.php';
    $api = new PayPalWebhookSetup($config);
    $hooks = $api->webhooks();
    $matches = array_values(array_filter($hooks, static fn($h) => ($h['url'] ?? '') === $url));
    echo 'PayPal authentication OK; environment: '.$config['paypal']['mode']."\n";
    echo 'Webhook URL: '.$url.'; matching subscriptions: '.count($matches)."\n";
    $ready = PayPalWebhookSetup::listenerReady($url);
    echo 'Deployed listener rejects unsigned events: '.($ready ? 'yes' : 'NO')."\n";
    if (!$ready) {
        throw new RuntimeException('Upload the updated webhook handler and PayPal integration first. No webhook was created or changed.');
    }
    if ($command === 'check') exit(0);
    $target = __DIR__.'/../src/config/paypal-webhook.php';
    if (!is_writable(dirname($target)) || (is_file($target) && !is_writable($target))) {
        throw new RuntimeException('The setup command must be able to write src/config/paypal-webhook.php.');
    }
    $hook = $api->ensure($url);
    $saved = ['mode' => $config['paypal']['mode'], 'client_id_hash' => hash('sha256', $config['paypal']['client_id']),
        'webhook_id' => $hook['id'], 'url' => $url];
    // A separate ignored file avoids rewriting or printing existing secrets.
    $temporary = tempnam(dirname($target), '.webhook-');
    if ($temporary === false) throw new RuntimeException('Webhook registered, but unable to save its local configuration. Rerun setup.');
    try {
        $contents = "<?php\n// Generated by the CLI; bound to this PayPal app and environment.\nreturn ".var_export($saved, true).";\n";
        if (file_put_contents($temporary, $contents, LOCK_EX) !== strlen($contents) || !rename($temporary, $target)) {
            throw new RuntimeException('Webhook registered, but configuration could not be saved. Rerun setup to recover the same subscription.');
        }
    } finally {
        if (is_file($temporary)) unlink($temporary);
    }
    echo 'Webhook registered and verified: '.$hook['id']."\n";
    echo "Saved src/config/paypal-webhook.php. No IPN setup or PayPal dashboard action is needed.\n";
    echo "A signed payment-event delivery still needs verification; no purchase was made by this command.\n";
} catch (Throwable $e) {
    fwrite(STDERR, $e->getMessage()."\n");
    exit(1);
}
